# 通过聚类算法将总的数据划分成相似的几个组

## 10个组

In [1]:
CLUSTER_NUMS = 10
TEST_SIZE = 0.3
RANDOM_STATE = 42

In [2]:
# 导库
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split

In [3]:
# 导入数据
data = pd.read_csv('../../data/data_magpie_training.csv')

In [4]:
data.head()

,material_id,formula_pretty,e_total,e_ionic,e_electronic,composition,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,mp-28967,Ba(PdS2)2,17.048334,7.118969,9.929365,Ba1 Pd2 S4,16.0,56.0,40.0,30.285714,...,0.000000,0.000000,0.000000,0.0,70.0,229.0,159.0,137.000000,76.571429,70.0
1,mp-766094,NbO2F,17.572010,13.469477,4.102533,Nb1 O2 F1,8.0,41.0,33.0,16.500000,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,67.000000,81.000000,12.0
2,mp-36577,Sr(AsS2)2,18.488667,12.443616,6.045051,Sr1 As2 S4,16.0,38.0,22.0,24.000000,...,0.000000,0.000000,0.000000,0.0,70.0,225.0,155.0,119.571429,56.653061,70.0
3,mp-1102092,NaFe(SO4)2,9.596025,6.499905,3.096120,Na1 Fe1 S2 O8,8.0,26.0,18.0,11.083333,...,2.110663,0.175889,0.322462,0.0,12.0,229.0,217.0,57.833333,61.111111,12.0
4,mp-720391,BH4NF4,6.216546,4.350314,1.866232,B1 H4 N1 F4,1.0,9.0,8.0,5.200000,...,0.000000,0.000000,0.000000,0.0,15.0,194.0,179.0,119.600000,83.680000,15.0

In [5]:
X = data.drop(columns=['material_id', 'composition', 'formula_pretty'])
y = data['e_ionic']

In [6]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7277 entries, 0 to 7276
Columns: 135 entries, e_total to MagpieData mode SpaceGroupNumber
dtypes: float64(135)
memory usage: 7.5 MB

- 先进行训练集和测试集划分

In [7]:
# 训练集测试集划分
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE)

In [8]:
kmeans = KMeans(n_clusters=CLUSTER_NUMS, random_state=RANDOM_STATE)

In [9]:
kmeans.fit(X_train)

e:\software2\Anaconda\envs\pytorchEnv\lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)

KMeans(n_clusters=10, random_state=42)

In [10]:
X_train['cluster'] = kmeans.labels_

In [11]:
# 预测测试集中每一个样本的类别
X_test['cluster'] = kmeans.predict(X_test)

In [12]:
X_test.head()

,e_total,e_ionic,e_electronic,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,cluster
6059,14.078999,6.862966,7.216033,3.0,25.0,22.0,12.769231,7.372781,8.0,1.0,...,0.000072,0.000110,0.0,12.0,229.0,217.0,92.692308,99.313609,12.0,6
6010,23.198326,15.958896,7.239430,8.0,57.0,49.0,29.750000,18.166667,16.0,13.0,...,0.000026,0.000047,0.0,12.0,217.0,205.0,118.750000,66.541667,70.0,0
4475,21.690907,11.098378,10.592529,29.0,57.0,28.0,38.500000,9.250000,34.0,13.0,...,0.000000,0.000000,0.0,14.0,225.0,211.0,111.750000,97.750000,14.0,7
3689,37.388675,30.495613,6.893062,1.0,20.0,19.0,8.857143,6.367347,6.0,1.0,...,0.000000,0.000000,0.0,194.0,229.0,35.0,207.857143,15.836735,194.0,8
4515,11.310439,3.828769,7.481670,13.0,47.0,34.0,29.400000,9.040000,34.0,65.0,...,0.000000,0.000000,0.0,2.0,225.0,223.0,53.800000,68.480000,14.0,7

In [13]:
groups = X_train.groupby('cluster')

In [14]:
for cluster, df in groups:
    print(f'Cluster {cluster}: {len(df)} samples')
    display(df.head(5))

Cluster 0: 966 samples

,e_total,e_ionic,e_electronic,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,cluster
952,20.756191,18.495867,2.260324,9.0,39.0,30.0,16.142857,10.204082,9.0,3.0,...,0.000000e+00,0.000000,0.0,15.0,229.0,214.0,68.642857,76.632653,15.0,0
1224,8.757306,4.390542,4.366764,7.0,14.0,7.0,10.000000,3.000000,7.0,68.0,...,0.000000e+00,0.000000,0.0,194.0,227.0,33.0,202.250000,12.375000,194.0,0
4559,12.757161,9.513923,3.243238,8.0,37.0,29.0,21.384615,11.029586,8.0,3.0,...,3.247174e-01,0.549522,0.0,12.0,229.0,217.0,145.538462,102.721893,12.0,0
2004,8.075949,5.988104,2.087845,9.0,37.0,28.0,16.800000,9.360000,9.0,3.0,...,6.350000e-07,0.000001,0.0,15.0,229.0,214.0,97.100000,98.520000,15.0,0
497,981.669996,977.424942,4.245054,8.0,21.0,13.0,15.333333,4.888889,8.0,11.0,...,2.116667e-06,0.000003,0.0,12.0,194.0,182.0,90.000000,69.333333,12.0,0

Cluster 1: 1 samples

,e_total,e_ionic,e_electronic,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,cluster
260,57262.630716,10404.720206,46857.91051,33.0,41.0,8.0,37.0,4.0,33.0,47.0,...,0.0,0.0,0.0,166.0,229.0,63.0,197.5,31.5,166.0,1

Cluster 2: 353 samples

,e_total,e_ionic,e_electronic,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,cluster
6157,30.141843,5.864121,24.277722,15.0,34.0,19.0,25.333333,6.888889,15.0,58.0,...,0.516157,0.688209,0.0,2.0,194.0,192.0,70.000000,82.666667,2.0,2
3734,10.264583,3.413772,6.850811,16.0,37.0,21.0,24.666667,7.703704,16.0,4.0,...,0.198465,0.264620,0.0,70.0,229.0,159.0,157.000000,77.333333,70.0,2
2413,25.336137,16.728654,8.607483,16.0,50.0,34.0,27.600000,13.920000,16.0,44.0,...,0.000000,0.000000,0.0,70.0,194.0,124.0,109.000000,46.800000,70.0,2
1756,12.164798,6.676055,5.488743,25.0,55.0,30.0,36.833333,6.777778,34.0,5.0,...,0.000052,0.000086,0.0,14.0,229.0,215.0,113.666667,99.666667,14.0,2
2577,13.502731,1.632385,11.870346,14.0,52.0,38.0,38.800000,15.840000,52.0,49.0,...,0.000000,0.000000,0.0,152.0,229.0,77.0,182.400000,36.480000,152.0,2

Cluster 3: 443 samples

,e_total,e_ionic,e_electronic,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,cluster
2154,46.967161,42.005900,4.961261,8.0,73.0,65.0,25.400000,21.760000,8.0,9.0,...,6.350000e-07,0.000001,0.0,12.0,229.0,217.0,95.300000,99.960000,12.0,3
564,10.471226,5.278071,5.193154,3.0,73.0,70.0,13.250000,14.937500,3.0,1.0,...,0.000000e+00,0.000000,0.0,194.0,229.0,35.0,215.875000,16.406250,229.0,3
6717,7.511627,4.401495,3.110131,8.0,74.0,66.0,21.800000,20.880000,9.0,51.0,...,0.000000e+00,0.000000,0.0,12.0,229.0,217.0,57.200000,68.720000,15.0,3
4985,8.004854,5.244014,2.760840,6.0,56.0,50.0,17.200000,15.520000,8.0,9.0,...,0.000000e+00,0.000000,0.0,12.0,229.0,217.0,91.800000,95.760000,12.0,3
1278,10.694042,7.491098,3.202945,8.0,73.0,65.0,18.571429,13.591837,8.0,3.0,...,0.000000e+00,0.000000,0.0,12.0,229.0,217.0,88.642857,98.540816,12.0,3

Cluster 4: 987 samples

,e_total,e_ionic,e_electronic,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,cluster
1344,9.885204,6.939711,2.945493,17.0,82.0,65.0,32.666667,20.888889,17.0,5.0,...,0.0,0.0,0.0,64.0,229.0,165.0,118.555556,72.740741,64.0,4
2932,48.638730,41.993581,6.645149,8.0,83.0,75.0,48.000000,26.666667,8.0,86.0,...,0.0,0.0,0.0,12.0,64.0,52.0,29.333333,23.111111,12.0,4
4294,14.106113,10.614688,3.491425,8.0,37.0,29.0,27.333333,12.888889,37.0,4.0,...,0.0,0.0,0.0,12.0,229.0,217.0,156.666667,96.444444,229.0,4
142,5.899325,3.041403,2.857923,1.0,81.0,80.0,16.000000,13.800000,1.0,76.0,...,0.0,0.0,0.0,64.0,194.0,130.0,142.000000,62.400000,64.0,4
1194,9.086700,5.299192,3.787509,8.0,50.0,42.0,14.750000,8.812500,11.0,2.0,...,0.0,0.0,0.0,12.0,229.0,217.0,136.625000,93.468750,229.0,4

Cluster 5: 1 samples

,e_total,e_ionic,e_electronic,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,cluster
5112,25244.446111,95.629586,25148.816525,34.0,51.0,17.0,40.25,7.3125,34.0,70.0,...,0.0,0.0,0.0,14.0,194.0,180.0,87.0,66.25,14.0,5

Cluster 6: 845 samples

,e_total,e_ionic,e_electronic,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,cluster
5456,11.347476,7.620234,3.727241,8.0,42.0,34.0,17.090909,13.223140,8.0,44.0,...,0.000000,0.000000,0.0,12.0,229.0,217.0,68.0,81.454545,12.0,6
4169,6.898910,4.268476,2.630435,3.0,8.0,5.0,5.428571,2.204082,3.0,1.0,...,0.000000,0.000000,0.0,12.0,229.0,217.0,127.0,98.571429,12.0,6
2571,18.658185,2.437054,16.221130,8.0,78.0,70.0,30.700000,28.380000,8.0,52.0,...,0.000031,0.000056,0.0,12.0,225.0,213.0,96.4,101.280000,12.0,6
1121,8.007591,4.384588,3.623003,8.0,24.0,16.0,11.333333,4.444444,8.0,49.0,...,0.000000,0.000000,0.0,12.0,229.0,217.0,78.5,88.666667,12.0,6
4101,7.109191,0.290551,6.818641,16.0,41.0,25.0,28.500000,6.250000,29.0,47.0,...,0.000000,0.000000,0.0,14.0,229.0,215.0,134.0,92.000000,225.0,6

Cluster 7: 635 samples

,e_total,e_ionic,e_electronic,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,cluster
2628,5.369542,2.132453,3.237090,20.0,53.0,33.0,42.000000,14.666667,53.0,7.0,...,0.0,0.0,0.0,64.0,225.0,161.0,117.666667,71.555556,64.0,7
3014,20.952346,13.461579,7.490766,16.0,59.0,43.0,31.428571,17.632653,16.0,8.0,...,0.0,0.0,0.0,70.0,225.0,155.0,127.571429,65.795918,70.0,7
1504,23.350282,6.960672,16.389610,12.0,32.0,20.0,18.666667,8.888889,12.0,68.0,...,0.0,0.0,0.0,194.0,225.0,31.0,204.333333,13.777778,194.0,7
7236,22.242846,7.053970,15.188876,33.0,48.0,15.0,38.000000,6.666667,33.0,70.0,...,0.0,0.0,0.0,166.0,194.0,28.0,175.333333,12.444444,166.0,7
1490,23.761439,1.448506,22.312932,30.0,51.0,21.0,45.500000,7.750000,51.0,69.0,...,0.0,0.0,0.0,141.0,194.0,53.0,166.750000,13.625000,166.0,7

Cluster 8: 69 samples

,e_total,e_ionic,e_electronic,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,cluster
5192,38.018395,17.898603,20.119792,14.0,44.0,30.0,24.000000,13.333333,14.0,56.0,...,0.000000,0.000000,0.0,194.0,227.0,33.0,216.000000,14.666667,227.0,8
903,28.905888,7.547979,21.357909,33.0,77.0,44.0,47.666667,19.555556,33.0,60.0,...,0.000000,0.000000,0.0,166.0,225.0,59.0,185.666667,26.222222,166.0,8
944,65.745971,42.619661,23.126310,32.0,76.0,44.0,49.600000,21.120000,32.0,57.0,...,0.000000,0.000000,0.0,194.0,225.0,31.0,212.600000,14.880000,225.0,8
2942,149.680468,29.658347,120.022121,21.0,44.0,23.0,37.500000,8.250000,44.0,11.0,...,0.000002,0.000002,0.0,194.0,229.0,35.0,202.750000,13.125000,194.0,8
350,40.378728,10.924966,29.453762,13.0,77.0,64.0,47.000000,30.000000,77.0,11.0,...,0.000002,0.000002,0.0,194.0,225.0,31.0,217.250000,11.625000,225.0,8

Cluster 9: 793 samples

,e_total,e_ionic,e_electronic,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,cluster
7036,8.808742,5.420374,3.388368,8.0,32.0,24.0,13.600000,7.360000,8.0,68.0,...,0.0,0.0,0.0,12.0,225.0,213.0,91.000000,94.800000,12.0,9
4557,9.044130,4.142382,4.901747,7.0,31.0,24.0,12.250000,5.250000,7.0,73.0,...,0.0,0.0,0.0,64.0,225.0,161.0,189.375000,31.343750,194.0,9
416,6.272033,2.708066,3.563967,9.0,83.0,74.0,21.400000,19.840000,9.0,65.0,...,0.0,0.0,0.0,12.0,225.0,213.0,28.600000,26.186667,15.0,9
6127,39.010562,5.980934,33.029628,1.0,50.0,49.0,30.000000,14.500000,1.0,8.0,...,0.0,0.0,0.0,64.0,225.0,161.0,156.000000,53.500000,64.0,9
1496,13.790363,9.318285,4.472078,8.0,57.0,49.0,22.666667,19.555556,8.0,13.0,...,0.0,0.0,0.0,12.0,194.0,182.0,64.888889,70.518519,12.0,9

In [15]:
# 保存数据
X_train['class'] = 'train'
X_test['class'] = 'test'
display(X_train.head())
display(X_test.head())

,e_total,e_ionic,e_electronic,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,cluster,class
2628,5.369542,2.132453,3.237090,20.0,53.0,33.0,42.000000,14.666667,53.0,7.0,...,0.000000,0.0,64.0,225.0,161.0,117.666667,71.555556,64.0,7,train
3014,20.952346,13.461579,7.490766,16.0,59.0,43.0,31.428571,17.632653,16.0,8.0,...,0.000000,0.0,70.0,225.0,155.0,127.571429,65.795918,70.0,7,train
2154,46.967161,42.005900,4.961261,8.0,73.0,65.0,25.400000,21.760000,8.0,9.0,...,0.000001,0.0,12.0,229.0,217.0,95.300000,99.960000,12.0,3,train
1344,9.885204,6.939711,2.945493,17.0,82.0,65.0,32.666667,20.888889,17.0,5.0,...,0.000000,0.0,64.0,229.0,165.0,118.555556,72.740741,64.0,4,train
7036,8.808742,5.420374,3.388368,8.0,32.0,24.0,13.600000,7.360000,8.0,68.0,...,0.000000,0.0,12.0,225.0,213.0,91.000000,94.800000,12.0,9,train

,e_total,e_ionic,e_electronic,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,cluster,class
6059,14.078999,6.862966,7.216033,3.0,25.0,22.0,12.769231,7.372781,8.0,1.0,...,0.000110,0.0,12.0,229.0,217.0,92.692308,99.313609,12.0,6,test
6010,23.198326,15.958896,7.239430,8.0,57.0,49.0,29.750000,18.166667,16.0,13.0,...,0.000047,0.0,12.0,217.0,205.0,118.750000,66.541667,70.0,0,test
4475,21.690907,11.098378,10.592529,29.0,57.0,28.0,38.500000,9.250000,34.0,13.0,...,0.000000,0.0,14.0,225.0,211.0,111.750000,97.750000,14.0,7,test
3689,37.388675,30.495613,6.893062,1.0,20.0,19.0,8.857143,6.367347,6.0,1.0,...,0.000000,0.0,194.0,229.0,35.0,207.857143,15.836735,194.0,8,test
4515,11.310439,3.828769,7.481670,13.0,47.0,34.0,29.400000,9.040000,34.0,65.0,...,0.000000,0.0,2.0,225.0,223.0,53.800000,68.480000,14.0,7,test

In [16]:
X_save = pd.concat([X_train, X_test])
X_save.head()
X_save.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7277 entries, 2628 to 6415
Columns: 137 entries, e_total to class
dtypes: float64(135), int32(1), object(1)
memory usage: 7.6+ MB

In [17]:
# 保存X_save
X_save.to_csv('../../data/groups/composition_features_groups/data_clusters_ionic.csv', index=False)